export const SET_CURRENT_USER_NAME = 'SET_CURRENT_USER_NAME';
export const SET_VALID_USER_DATA = 'SET_VALID_USER_DATA';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const DELETE_FROM_FAVORITES = 'DELETE_FROM_FAVORITES';
export const SHOW_RECIPE_DETAILS = 'SHOW_RECIPE_DETAILS';
export const ADD_RECIPE = 'ADD_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const UPDATE_LIKES = 'UPDATE_LIKES';
